
//: * [UIView 动画](UIViewAnimation)
//: * [核心动画-基础](CoreAnimation-Basic)
//: * [核心动画-动画类](CoreAnimation-Animation%20Class)
//: * [核心动画-CAAction](CoreAnimation-CAAction)
//: * [核心动画-CATransaction](CoreAnimation-CATransaction)
//: * [CAShapeLayer深入第一部分](CAShapeLayer%20in%20Depth%20Part%20I)
//: * [CAShapeLayer深入第二部分](CAShapeLayer%20in%20Depth%20Part%20II)
//: * [延迟动画循环](Delaying%20Animation%20Loops)
//: * [使用 UIBezierPath 绘制圆形路径](Use%20UIBezierPath%20Draw%20Circle%20Path)
